import { format } from 'date-fns';
import { Partido, Usuario, Inscripcion, ChatMessage, AppNotification, MatchReview } from '@/types/database';

export const INITIAL_USERS: Usuario[] = [
  {
    id: 'usr-nahuel-1',
    nombre: 'Nahuel Rabbiosi',
    email: 'nahuel@juntadafutbol.com',
    email_verificado: true,
    telefono: '+54 9 11 4567-8901',
    telefono_verificado: true,
    zona: 'Palermo, CABA',
    posicion_preferida: 'mediocampista',
    rating: 4.9,
    avatar_url: null,
    created_at: new Date().toISOString(),
    partidos_jugados: 34,
    asistencia_pct: 98,
    medallas: ['Asistencia perfecta', 'Buen compañero', 'Organizador confiable'],
    edad_aprox: 28,
    verificado: true,
    infracciones: 0,
    sancion_hasta: null,
    bloqueados: [],
  },
  {
    id: 'usr-lucas-2',
    nombre: 'Lucas Fernández',
    email: 'lucas.f@gmail.com',
    email_verificado: true,
    telefono: '+54 9 11 6789-0123',
    telefono_verificado: true,
    zona: 'Caballito, CABA',
    posicion_preferida: 'delantero',
    rating: 4.8,
    avatar_url: null,
    created_at: new Date().toISOString(),
    partidos_jugados: 26,
    asistencia_pct: 96,
    medallas: ['Goleador', 'Juego limpio', 'Salvó el partido'],
    edad_aprox: 26,
    verificado: true,
    infracciones: 0,
    sancion_hasta: null,
    bloqueados: [],
  },
  {
    id: 'usr-matias-3',
    nombre: 'Matías Rossi',
    email: 'matias.arquero@hotmail.com',
    email_verificado: true,
    telefono: '+54 9 11 3456-7890',
    telefono_verificado: true,
    zona: 'Belgrano, CABA',
    posicion_preferida: 'arquero',
    rating: 5.0,
    avatar_url: null,
    created_at: new Date().toISOString(),
    partidos_jugados: 42,
    asistencia_pct: 100,
    medallas: ['Arquero estrella', 'Asistencia perfecta', 'MVP fecha'],
    edad_aprox: 31,
    verificado: true,
    infracciones: 0,
    sancion_hasta: null,
    bloqueados: [],
  },
  {
    id: 'usr-franco-4',
    nombre: 'Franco Silva',
    email: 'franco.silva@yahoo.com',
    email_verificado: false,
    telefono: '+54 9 11 2345-6789',
    telefono_verificado: false,
    zona: 'Villa Crespo, CABA',
    posicion_preferida: 'defensor',
    rating: 4.7,
    avatar_url: null,
    created_at: new Date().toISOString(),
    partidos_jugados: 19,
    asistencia_pct: 92,
    medallas: ['Muralla defensiva', 'Buen compañero'],
    edad_aprox: 25,
    verificado: false,
    infracciones: 1,
    sancion_hasta: null,
    bloqueados: [],
  },
  {
    id: 'usr-sofia-5',
    nombre: 'Sofía Martínez',
    email: 'sofia.martinez@gmail.com',
    email_verificado: true,
    telefono: '+54 9 11 5678-9012',
    telefono_verificado: true,
    zona: 'Colegiales, CABA',
    posicion_preferida: 'delantera',
    rating: 4.9,
    avatar_url: null,
    created_at: new Date().toISOString(),
    partidos_jugados: 21,
    asistencia_pct: 100,
    medallas: ['Asistencia perfecta', 'Juego limpio', 'Goleadora'],
    edad_aprox: 27,
    verificado: true,
    infracciones: 0,
    sancion_hasta: null,
    bloqueados: [],
  },
];

const now = new Date();
const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000);
tomorrow.setHours(20, 0, 0, 0);

const inTwoDays = new Date(now.getTime() + 48 * 60 * 60 * 1000);
inTwoDays.setHours(19, 30, 0, 0);

const saturday = new Date(now.getTime() + 72 * 60 * 60 * 1000);
saturday.setHours(16, 0, 0, 0);

const nextWeek = new Date(now.getTime() + 96 * 60 * 60 * 1000);
nextWeek.setHours(21, 0, 0, 0);

export const INITIAL_PARTIDOS: Partido[] = [
  {
    id: 'match-1',
    creador_id: 'usr-nahuel-1',
    titulo: 'Fútbol 5 nocturno en Palermo',
    cancha: 'Complejo El Predio (Palermo)',
    lat: -34.5802,
    lng: -58.4233,
    fecha_hora: tomorrow.toISOString(),
    jugadores_necesarios: 10,
    jugadores_confirmados: 8,
    estado: 'abierto',
    tipo_cancha: '5',
    notas: 'Llevar camiseta clara y oscura. Césped sintético con luces led nuevas. ¡Tercer tiempo con birras y pizzas!',
    created_at: now.toISOString(),
    genero: 'mixto',
    nivel: 'intermedio',
    precio_total: 30000,
    precio_por_persona: 3000,
    busca_arquero: true,
    arquero_gratis: true,
    servicios: ['sintetico', 'vestuarios', 'estacionamiento'],
    tercer_tiempo: true,
    medio_pago: 'transferencia',
    alias_cvu: 'nahuel.futbol.mp',
    equipos: {
      equipoA: ['usr-nahuel-1', 'usr-matias-3'],
      equipoB: ['usr-lucas-2', 'usr-franco-4'],
    },
    lista_espera: [],
    pagos_estado: {
      'usr-nahuel-1': 'pagado',
      'usr-lucas-2': 'pagado',
      'usr-matias-3': 'pendiente',
    },
    checkins: ['usr-nahuel-1', 'usr-lucas-2'],
    mvp_votos: {},
  },
  {
    id: 'match-2',
    creador_id: 'usr-nahuel-1',
    titulo: 'Fútbol 7 de jueves (Techado)',
    cancha: 'Club La Masía (Caballito)',
    lat: -34.6186,
    lng: -58.4438,
    fecha_hora: inTwoDays.toISOString(),
    jugadores_necesarios: 14,
    jugadores_confirmados: 12,
    estado: 'abierto',
    tipo_cancha: '7',
    notas: 'Cancha techada, se juega con lluvia. Hay vestuarios con agua caliente.',
    created_at: now.toISOString(),
    genero: 'masculino',
    nivel: 'competitivo',
    precio_total: 42000,
    precio_por_persona: 3000,
    busca_arquero: false,
    arquero_gratis: false,
    servicios: ['techada', 'sintetico', 'vestuarios'],
    tercer_tiempo: true,
    medio_pago: 'transferencia',
    alias_cvu: 'futbol.caballito.mp',
    equipos: null,
    lista_espera: [],
    pagos_estado: {
      'usr-nahuel-1': 'pagado',
    },
    checkins: ['usr-nahuel-1'],
    mvp_votos: {},
  },
  {
    id: 'match-3',
    creador_id: 'usr-sofia-5',
    titulo: 'Fútbol 5 Femenino en Belgrano',
    cancha: 'Punto Gol Belgrano',
    lat: -34.5610,
    lng: -58.4560,
    fecha_hora: saturday.toISOString(),
    jugadores_necesarios: 10,
    jugadores_confirmados: 9,
    estado: 'abierto',
    tipo_cancha: '5',
    notas: 'Picadito recreativo para divertirnos y pasarla bien. ¡Traer buena onda!',
    created_at: now.toISOString(),
    genero: 'femenino',
    nivel: 'recreativo',
    precio_total: 28000,
    precio_por_persona: 2800,
    busca_arquero: true,
    arquero_gratis: true,
    servicios: ['sintetico', 'vestuarios', 'estacionamiento'],
    tercer_tiempo: true,
    medio_pago: 'transferencia',
    alias_cvu: 'sofi.martinez.mp',
    equipos: null,
    lista_espera: [],
    pagos_estado: {
      'usr-sofia-5': 'pagado',
    },
    checkins: ['usr-sofia-5'],
    mvp_votos: {},
  },
  {
    id: 'match-4',
    creador_id: 'usr-lucas-2',
    titulo: 'Fútbol 11 fin de semana césped natural',
    cancha: 'Complejo Costanera Norte',
    lat: -34.5510,
    lng: -58.4180,
    fecha_hora: nextWeek.toISOString(),
    jugadores_necesarios: 22,
    jugadores_confirmados: 20,
    estado: 'abierto',
    tipo_cancha: '11',
    notas: 'Pasto natural con árbitro oficial. Canilleras obligatorias.',
    created_at: now.toISOString(),
    genero: 'masculino',
    nivel: 'competitivo',
    precio_total: 66000,
    precio_por_persona: 3000,
    busca_arquero: false,
    arquero_gratis: false,
    servicios: ['vestuarios', 'estacionamiento'],
    tercer_tiempo: false,
    medio_pago: 'efectivo',
    alias_cvu: null,
    equipos: null,
    lista_espera: [],
    pagos_estado: {},
    checkins: [],
    mvp_votos: {},
  },
  {
    id: 'match-past-1',
    creador_id: 'usr-nahuel-1',
    titulo: 'Fútbol 5 clásico de los martes',
    cancha: 'Complejo El Predio (Palermo)',
    lat: -34.5802,
    lng: -58.4233,
    fecha_hora: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    jugadores_necesarios: 10,
    jugadores_confirmados: 10,
    estado: 'finalizado',
    tipo_cancha: '5',
    notas: 'Partidazo 7 a 6 muy parejo con gran definición al final.',
    created_at: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    genero: 'mixto',
    nivel: 'intermedio',
    precio_total: 28000,
    precio_por_persona: 2800,
    busca_arquero: true,
    arquero_gratis: true,
    servicios: ['sintetico', 'vestuarios', 'estacionamiento'],
    tercer_tiempo: true,
    medio_pago: 'transferencia',
    alias_cvu: 'nahuel.futbol.mp',
    equipos: {
      equipoA: ['usr-nahuel-1', 'usr-matias-3', 'usr-sofia-5'],
      equipoB: ['usr-lucas-2', 'usr-franco-4'],
    },
    lista_espera: [],
    pagos_estado: {
      'usr-nahuel-1': 'pagado',
      'usr-lucas-2': 'pagado',
      'usr-matias-3': 'pagado',
    },
    checkins: ['usr-nahuel-1', 'usr-lucas-2', 'usr-matias-3'],
    mvp_votos: { 'usr-nahuel-1': 'usr-matias-3' },
  },
  {
    id: 'match-past-2',
    creador_id: 'usr-lucas-2',
    titulo: 'Fútbol 7 relámpago con tercer tiempo',
    cancha: 'Club La Masía (Caballito)',
    lat: -34.6186,
    lng: -58.4438,
    fecha_hora: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    jugadores_necesarios: 14,
    jugadores_confirmados: 14,
    estado: 'finalizado',
    tipo_cancha: '7',
    notas: 'Muy buen ritmo en cancha techada. Gran pizza en el bar al terminar.',
    created_at: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    genero: 'masculino',
    nivel: 'competitivo',
    precio_total: 42000,
    precio_por_persona: 3000,
    busca_arquero: false,
    arquero_gratis: false,
    servicios: ['techada', 'sintetico', 'vestuarios'],
    tercer_tiempo: true,
    medio_pago: 'transferencia',
    alias_cvu: 'futbol.caballito.mp',
    equipos: null,
    lista_espera: [],
    pagos_estado: {},
    checkins: ['usr-nahuel-1'],
    mvp_votos: {},
  },
  {
    id: 'match-past-3',
    creador_id: 'usr-sofia-5',
    titulo: 'Fútbol 5 recreativo de fin de semana',
    cancha: 'Punto Gol Belgrano',
    lat: -34.5610,
    lng: -58.4560,
    fecha_hora: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    jugadores_necesarios: 10,
    jugadores_confirmados: 10,
    estado: 'finalizado',
    tipo_cancha: '5',
    notas: 'Jornada a puro fútbol y compañerismo en Belgrano.',
    created_at: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    genero: 'femenino',
    nivel: 'recreativo',
    precio_total: 28000,
    precio_por_persona: 2800,
    busca_arquero: true,
    arquero_gratis: true,
    servicios: ['sintetico', 'vestuarios'],
    tercer_tiempo: true,
    medio_pago: 'transferencia',
    alias_cvu: 'sofi.martinez.mp',
    equipos: null,
    lista_espera: [],
    pagos_estado: {},
    checkins: [],
    mvp_votos: {},
  },
];

export const INITIAL_INSCRIPCIONES: Inscripcion[] = [
  {
    id: 'ins-1',
    partido_id: 'match-1',
    usuario_id: 'usr-nahuel-1',
    estado: 'confirmado',
    created_at: now.toISOString(),
  },
  {
    id: 'ins-2',
    partido_id: 'match-1',
    usuario_id: 'usr-lucas-2',
    estado: 'confirmado',
    created_at: now.toISOString(),
  },
  {
    id: 'ins-3',
    partido_id: 'match-1',
    usuario_id: 'usr-matias-3',
    estado: 'confirmado',
    created_at: now.toISOString(),
  },
  {
    id: 'ins-4',
    partido_id: 'match-1',
    usuario_id: 'usr-franco-4',
    estado: 'pendiente',
    created_at: now.toISOString(),
  },
  {
    id: 'ins-5',
    partido_id: 'match-2',
    usuario_id: 'usr-nahuel-1',
    estado: 'confirmado',
    created_at: now.toISOString(),
  },
  {
    id: 'ins-6',
    partido_id: 'match-2',
    usuario_id: 'usr-matias-3',
    estado: 'confirmado',
    created_at: now.toISOString(),
  },
  {
    id: 'ins-7',
    partido_id: 'match-3',
    usuario_id: 'usr-sofia-5',
    estado: 'confirmado',
    created_at: now.toISOString(),
  },
  {
    id: 'ins-past-1',
    partido_id: 'match-past-1',
    usuario_id: 'usr-nahuel-1',
    estado: 'confirmado',
    created_at: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ins-past-2',
    partido_id: 'match-past-1',
    usuario_id: 'usr-lucas-2',
    estado: 'confirmado',
    created_at: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ins-past-3',
    partido_id: 'match-past-1',
    usuario_id: 'usr-matias-3',
    estado: 'confirmado',
    created_at: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ins-past-4',
    partido_id: 'match-past-2',
    usuario_id: 'usr-nahuel-1',
    estado: 'confirmado',
    created_at: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ins-past-5',
    partido_id: 'match-past-3',
    usuario_id: 'usr-nahuel-1',
    estado: 'confirmado',
    created_at: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_CHATS: ChatMessage[] = [
  {
    id: 'msg-1',
    partido_id: 'match-1',
    usuario_id: 'usr-nahuel-1',
    usuario_nombre: 'Nahuel Rabbiosi',
    mensaje: '¡Hola muchachos y chicas! Yo llevo 2 pelotas número 5 infladas.',
    created_at: new Date(now.getTime() - 3600000).toISOString(),
  },
  {
    id: 'msg-2',
    partido_id: 'match-1',
    usuario_id: 'usr-lucas-2',
    usuario_nombre: 'Lucas Fernández',
    mensaje: 'De diez, yo llevo pecheras rojas y azules por si hace falta.',
    created_at: new Date(now.getTime() - 2400000).toISOString(),
  },
  {
    id: 'msg-3',
    partido_id: 'match-1',
    usuario_id: 'usr-matias-3',
    usuario_nombre: 'Matías Rossi',
    mensaje: 'Voy al arco como siempre 🧤. ¡Nos vemos 19:45 para elongar!',
    created_at: new Date(now.getTime() - 1200000).toISOString(),
  },
];

export const FREQUENT_COMPLEXES = [
  {
    nombre: 'Complejo El Predio (Palermo)',
    direccion: 'Av. Juan B. Justo 1650, Palermo, CABA',
    lat: -34.5802,
    lng: -58.4233,
    tipo: '5',
    servicios: ['sintetico', 'vestuarios', 'estacionamiento'] as const,
    techada: false,
    precioSugerido: 30000,
  },
  {
    nombre: 'Club La Masía (Caballito)',
    direccion: 'Av. Gaona 1240, Caballito, CABA',
    lat: -34.6186,
    lng: -58.4438,
    tipo: '7',
    servicios: ['techada', 'sintetico', 'vestuarios'] as const,
    techada: true,
    precioSugerido: 42000,
  },
  {
    nombre: 'Punto Gol Belgrano',
    direccion: 'Monroe 1420, Belgrano, CABA',
    lat: -34.5610,
    lng: -58.4560,
    tipo: '5',
    servicios: ['sintetico', 'vestuarios', 'estacionamiento'] as const,
    techada: false,
    precioSugerido: 28000,
  },
  {
    nombre: 'Complejo Costanera Norte',
    direccion: 'Av. Costanera Rafael Obligado 1800, CABA',
    lat: -34.5510,
    lng: -58.4180,
    tipo: '11',
    servicios: ['vestuarios', 'estacionamiento'] as const,
    techada: false,
    precioSugerido: 66000,
  },
  {
    nombre: 'Open Gallo (Almagro)',
    direccion: 'Gallo 450, Almagro, CABA',
    lat: -34.6042,
    lng: -58.4187,
    tipo: '5',
    servicios: ['techada', 'sintetico', 'vestuarios'] as const,
    techada: true,
    precioSugerido: 32000,
  },
];

export const INITIAL_NOTIFICACIONES: AppNotification[] = [
  {
    id: 'notif-1',
    usuario_id: 'usr-nahuel-1',
    partido_id: 'match-1',
    partido_titulo: 'Fútbol 5 nocturno en Palermo',
    titulo: '⏰ Horario actualizado',
    mensaje: 'El organizador ajustó el horario para mañana: 20:30 hs (antes 20:00 hs) para asegurar cancha 1 techada.',
    tipo: 'horario_cambiado',
    leido: false,
    created_at: new Date(now.getTime() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-2',
    usuario_id: 'usr-nahuel-1',
    partido_id: 'match-4',
    partido_titulo: 'Fútbol 11 fin de semana césped natural',
    titulo: '⚠️ Partido cancelado por alerta climática',
    mensaje: 'El partido en Costanera Norte fue cancelado por pronóstico de tormenta y fuertes vientos. Tu saldo no fue afectado.',
    tipo: 'cancelado',
    leido: false,
    created_at: new Date(now.getTime() - 120 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-3',
    usuario_id: 'usr-nahuel-1',
    partido_id: 'match-past-1',
    partido_titulo: 'Fútbol 5 clásico de los martes',
    titulo: '⭐ ¿Cómo estuvo el partido?',
    mensaje: 'Participaste en "Fútbol 5 clásico de los martes". ¡Dejá tu valoración en tu perfil para ayudar a la comunidad!',
    tipo: 'recordatorio',
    leido: true,
    created_at: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_REVIEWS: MatchReview[] = [
  {
    id: 'rev-1',
    partido_id: 'match-past-1',
    partido_titulo: 'Fútbol 5 clásico de los martes',
    usuario_id: 'usr-nahuel-1',
    rating: 5,
    comentario: 'Excelente nivel, todos llegaron puntuales y el tercer tiempo con pizzas estuvo genial.',
    tags: ['Puntualidad', 'Buena onda', 'Cancha impecable', 'Tercer tiempo top'],
    created_at: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_TURNOS_FLASH: any[] = [
  {
    id: 'flash-1',
    complejo_id: 'cplx-asturiano',
    complejo_nombre: 'Centro Asturiano (Vicente López)',
    cancha_nombre: 'Cancha 3 - Techada Sintético Pro',
    tipo_cancha: 'Fútbol 5',
    superficie: 'Césped Sintético Forbex con caucho',
    direccion: 'Av. del Libertador 1081, Vicente López',
    zona: 'Vicente López, Buenos Aires',
    fecha: format(now, 'yyyy-MM-dd'),
    hora: '21:00 hs',
    precio_regular: 36000,
    precio_oferta: 23400,
    descuento_pct: 35,
    motivo_cancelacion: 'Grupo avisó hace 20 min que no llegan por viaje de trabajo.',
    reservado: false,
    codigo_reserva: 'F1-FLASH-9412',
    qr_validado: false,
    created_at: new Date(now.getTime() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'flash-2',
    complejo_id: 'cplx-open-gallo',
    complejo_nombre: 'Open Gallo Fútbol',
    cancha_nombre: 'Cancha Central Techada',
    tipo_cancha: 'Fútbol 5',
    superficie: 'Pasto sintético techado con iluminación LED',
    direccion: 'Gallo 450, Almagro, CABA',
    zona: 'Almagro, CABA',
    fecha: format(now, 'yyyy-MM-dd'),
    hora: '22:30 hs',
    precio_regular: 34000,
    precio_oferta: 20400,
    descuento_pct: 40,
    motivo_cancelacion: 'Cancelación de último momento por superposición de torneo.',
    reservado: false,
    codigo_reserva: 'F1-FLASH-8120',
    qr_validado: false,
    created_at: new Date(now.getTime() - 50 * 60 * 1000).toISOString(),
  },
  {
    id: 'flash-3',
    complejo_id: 'cplx-salguero',
    complejo_nombre: 'Salguero Fútbol & Pádel',
    cancha_nombre: 'Cancha 2 - Fútbol 7 Panorámica',
    tipo_cancha: 'Fútbol 7',
    superficie: 'Césped sintético premium',
    direccion: 'Jerónimo Salguero 3450, Palermo, CABA',
    zona: 'Palermo, CABA',
    fecha: format(new Date(now.getTime() + 24 * 60 * 60 * 1000), 'yyyy-MM-dd'),
    hora: '20:00 hs',
    precio_regular: 48000,
    precio_oferta: 33600,
    descuento_pct: 30,
    motivo_cancelacion: 'Turno liberado por reprogramación médica del titular.',
    reservado: false,
    codigo_reserva: 'F1-FLASH-7301',
    qr_validado: false,
    created_at: new Date(now.getTime() - 75 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_COMMUNITY_POSTS: any[] = [
  {
    id: 'post-1',
    autor_id: 'usr-lucas-2',
    autor_nombre: 'Lucas Fernández',
    autor_tipo: 'jugador',
    categoria: 'busco_rival',
    titulo: '🔥 Se busca rival Fútbol 5 para HOY 21:30hs en Palermo',
    contenido: 'Tenemos cancha reservada en Salguero Fútbol. Somos un equipo intermedio, dinámico y con muy buena onda. Jugamos a pechear con el alquiler 50/50 y tercer tiempo optativo.',
    zona: 'Palermo, CABA',
    fecha_partido: 'Hoy 21:30 hs',
    contacto: '+54 9 11 6789-0123',
    likes: ['usr-nahuel-1', 'usr-matias-3', 'usr-franco-4'],
    created_at: new Date(now.getTime() - 40 * 60 * 1000).toISOString(),
  },
  {
    id: 'post-2',
    autor_id: 'cplx-salguero',
    autor_nombre: 'Salguero Fútbol',
    autor_tipo: 'complejo',
    complejo_nombre: 'Salguero Fútbol & Pádel',
    categoria: 'torneo',
    titulo: '🏆 Torneo Relámpago Clausura Fútbol 7 - Este Sábado',
    contenido: 'Inscripciones abiertas para 16 equipos. Premios: Juego completo de indumentaria deportiva + Trofeo + Asado para todo el plantel campeón. ¡Cupos limitados!',
    zona: 'Palermo, CABA',
    fecha_partido: 'Sábado 15:00 hs',
    contacto: 'info@salguerofutbol.com / 11 4455-8899',
    likes: ['usr-nahuel-1', 'usr-sofia-5'],
    created_at: new Date(now.getTime() - 150 * 60 * 1000).toISOString(),
  },
  {
    id: 'post-3',
    autor_id: 'usr-matias-3',
    autor_nombre: 'Matías Rossi (Arquero)',
    autor_tipo: 'jugador',
    categoria: 'busco_jugador',
    titulo: '🧤 Arquero disponible zona Belgrano / Colegiales / Núñez',
    contenido: 'Buenas gente, estoy libre para atajar hoy después de las 20hs o mañana todo el día. Calidad de guantes, salida prolija y voy gratis si falta uno.',
    zona: 'Belgrano, CABA',
    fecha_partido: 'Hoy o Mañana',
    contacto: '+54 9 11 3456-7890',
    likes: ['usr-nahuel-1', 'usr-lucas-2'],
    created_at: new Date(now.getTime() - 210 * 60 * 1000).toISOString(),
  },
  {
    id: 'post-4',
    autor_id: 'cplx-open-gallo',
    autor_nombre: 'Open Gallo Almagro',
    autor_tipo: 'complejo',
    complejo_nombre: 'Open Gallo',
    categoria: 'turno_libre',
    titulo: '⚡ Cancha liberada con 40% OFF - Fútbol 5 techada hoy 22:30hs',
    contenido: 'Cancha 1 con vestuarios renovados y buffet abierto. Ideal si te quedaste sin jugar. ¡Reservá directo desde el botón de la app!',
    zona: 'Almagro, CABA',
    fecha_partido: 'Hoy 22:30 hs',
    contacto: 'open-gallo@canchas.ar',
    likes: ['usr-nahuel-1'],
    created_at: new Date(now.getTime() - 15 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_TEAM_PROFILES: any[] = [
  {
    id: 'team-galacticos',
    nombre: 'Los Galácticos de Palermo',
    escudo_emoji: '⚡',
    color_camiseta: '#00F0FF',
    modalidad: 5,
    zona: 'Palermo, CABA',
    nivel: 'intermedio',
    capitan_id: 'usr-nahuel-1',
    capitan_nombre: 'Nahuel Rabbiosi',
    jugadores_count: 7,
    victorias: 14,
    derrotas: 4,
    empates: 2,
    created_at: new Date(now.getTime() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'team-aston-birra',
    nombre: 'Aston Birra FC',
    escudo_emoji: '🍺',
    color_camiseta: '#FFD700',
    modalidad: 5,
    zona: 'Caballito, CABA',
    nivel: 'intermedio',
    capitan_id: 'usr-lucas-2',
    capitan_nombre: 'Lucas Fernández',
    jugadores_count: 6,
    victorias: 11,
    derrotas: 6,
    empates: 3,
    created_at: new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'team-scaloneta-norte',
    nombre: 'La Scaloneta del Norte',
    escudo_emoji: '🏆',
    color_camiseta: '#00E676',
    modalidad: 7,
    zona: 'Vicente López, Buenos Aires',
    nivel: 'competitivo',
    capitan_id: 'usr-matias-3',
    capitan_nombre: 'Matías Rossi',
    jugadores_count: 10,
    victorias: 19,
    derrotas: 3,
    empates: 1,
    created_at: new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'team-sacachispas-urquiza',
    nombre: 'Sacachispas de Urquiza',
    escudo_emoji: '🔥',
    color_camiseta: '#FF3366',
    modalidad: 5,
    zona: 'Villa Urquiza, CABA',
    nivel: 'recreativo',
    capitan_id: 'usr-franco-4',
    capitan_nombre: 'Franco Silva',
    jugadores_count: 8,
    victorias: 8,
    derrotas: 9,
    empates: 4,
    created_at: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_TEAM_CHALLENGES: any[] = [
  {
    id: 'chal-1',
    equipo_desafiante: {
      id: 'team-aston-birra',
      nombre: 'Aston Birra FC',
      escudo_emoji: '🍺',
      capitan_id: 'usr-lucas-2',
      capitan_nombre: 'Lucas Fernández',
      modalidad: 5,
      zona: 'Caballito, CABA',
    },
    equipo_rival: {
      id: 'team-galacticos',
      nombre: 'Los Galácticos de Palermo',
      escudo_emoji: '⚡',
      capitan_id: 'usr-nahuel-1',
      capitan_nombre: 'Nahuel Rabbiosi',
    },
    predio_sugerido: 'Salguero Fútbol (Cancha 1)',
    fecha_sugerida: 'Viernes 21:00 hs',
    mensaje: '¿Sale revancha del clásico? ¡Llevamos la pelota y el que pierde paga la primer ronda del 3er tiempo!',
    estado: 'pendiente',
    created_at: new Date(now.getTime() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'chal-2',
    equipo_desafiante: {
      id: 'team-sacachispas-urquiza',
      nombre: 'Sacachispas de Urquiza',
      escudo_emoji: '🔥',
      capitan_id: 'usr-franco-4',
      capitan_nombre: 'Franco Silva',
      modalidad: 5,
      zona: 'Villa Urquiza, CABA',
    },
    equipo_rival: {
      id: 'team-galacticos',
      nombre: 'Los Galácticos de Palermo',
      escudo_emoji: '⚡',
      capitan_id: 'usr-nahuel-1',
      capitan_nombre: 'Nahuel Rabbiosi',
    },
    predio_sugerido: 'Open Gallo Almagro',
    fecha_sugerida: 'Sábado 19:30 hs',
    mensaje: 'Desafío amistoso para probar arquero nuevo. ¿Se prenden?',
    estado: 'aceptado',
    created_at: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
  },
];


